name: "postgres-db"

services:
  postgres:
    image: pgvector/pgvector:pg18-trixie
    container_name: "postgres"
    ports:
      - 5432:5432
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
      - ~/apps/posgres:/var/lib/posgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
